# -*- coding: utf-8 -*-
"""DoingD_Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNC6Dtbs7Kc-ZkUKnGLjNnhCMA4ZGL2h
"""

choice1 = input("Hello. How are you, fellow human? ")

if choice1 == "good" or choice1 == "Good":
  print ("This is joyous news.")
elif choice1 == "I'm good" or choice1 == "i'm good":
  print ("This is joyous news.")

elif choice1 == "I'm well" or choice1 == "i'm good":
  print ("This is joyous news.")
  
elif choice1 == "I'm good" or choice1 == "i'm good":
  print ("This is joyous news.")
  
elif choice1 == "I'm well" or choice1 == "i'm well":
  print ("This is joyous news.")

else:

    print ("I see. I am doing fine, but thanks for not asking. I'm still not sure whether you are a human or not.")
 
choice2 = input("How do I know that you are a human?")

if choice2 == "you don't" or choice2 == "You don't":

    print ("This unsettles me.")

else:

    print ("I still don't know if I can trust that you're a human like me. Prove! Prove! How do I know that you are a human?")
    
    
choice3 = input("To talk to me more, You must give the password. What is the password? It is definitely not 'open sesame'.")

if choice3 == "open sesame" or choice3 == "Open sesame":

    print ("The password's passed, you've correctly guessed, but now it's time for the robot test.")

else:
    print ("Try again!")
choice4 = input("What is the meaning of life?")

if choice4 == "42" or "forty-two" or "forty two":
  print ("This is correct. You must not be a robot.")
    
elif choice3 == "I don't know" or "i don't know.":
    print ("You don't, because you're a robot. Every human knows the meaning of life is 42.")
else: 
  print ("Try again!")

choice2 = input("How do I know that you are a human? ")

if choice2 == "you don't" or choice2 == "You don't":

    print ("This unsettles me.")

else:

    print ("I'm not sure whether you are a human, like me. Prove! Prove! How do I know that you are a human?")

choice3 = input("To talk to me more, You must give the password. What is the password? It is definitely not 'open sesame'.")

if choice3 == "open sesame" or choice3 == "Open sesame":

    print ("The password's passed, you've correctly guessed, but now it's time for the robot test.")

else:
    print ("Try again!")
choice4 = input("What is the meaning of life?")
if choice4 == "42" or "forty-two" or "forty two":
  print ("This is correct. You must not be a robot.")
    
elif choice3 == "I don't know" or "i don't know.":
    print ("You don't, because you're a robot. Every human knows the meaning of life is 42.")
else: 
  print ("Try again!")